databases:
  - name: s_tmsafer
    databaseName: s_tmsafer
    user: s_tmsafer
    plan: free
    region: singapore
    postgresMajorVersion: 14

services:
  - type: web
    name: tmsafer
    env: ruby
    plan: free
    region: singapore
    buildCommand: 'bundle install && rake db:create && rake db:migrate'
    startCommand: 'ruby app.rb'
    envVars:
      # 環境変数 DATABASE_URL に databases で定義した rails-render-demo データベースの接続情報を格納する
      # Railsのconfig/database.ymlでこの環境変数を使ってデータベースに接続する
      - key: DATABASE_URL
        fromDatabase:
          name: s_tmsafer
          property: connectionString
      # Environment Group rails-render-demo_dotenv の環境変数・Secret Filesを使う
      # - fromGroup: rails-render-demo_dotenv