default_env: &default
  adapter: postgresql
  encoding: unicode
  database: s_tmsafer
  timeout: 5000
  host: localhost
  port: 5432

development:
  <<: *default
  database: s_tmsafer

production:
  <<: *default
  host: <%= ENV['DATABASE_HOST'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  username: <%= ENV['DATABASE_USERNAME'] %>
  database: s_tmsafer