default_env: &default
  adapter: postgresql
  encoding: unicode
  database: s_tmsafer
  timeout: 5000
  host: localhost
  port: 5432

development:
  <<: *default
  database: s_tmsafer

production:
  <<: *default
  password: <%= ENV['DATABASE_PASSWORD'] %>
  username: ajj-k
  database: s_tmsafer